# Docker Compose for Bot Factory Maker
# ملف Docker Compose لتسهيل النشر مع MongoDB

version: '3.8'

services:
  bot-factory:
    build: .
    container_name: bot-factory
    restart: unless-stopped
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGO_DB_URI=${MONGO_DB_URI}
      - OWNER_ID=${OWNER_ID}
      - CHANNEL=${CHANNEL}
      - GROUP=${GROUP}
      - PHOTO=${PHOTO}
      - VIDEO=${VIDEO}
      - LOGS=${LOGS}
    volumes:
      - ./Maked:/app/Maked
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - bot-network

  mongodb:
    image: mongo:6.0
    container_name: bot-factory-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=bot_factory
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - bot-network

volumes:
  mongodb_data:

networks:
  bot-network:
    driver: bridge