# Docker Compose for Bot Factory Maker
# ملف Docker Compose لتسهيل النشر مع MongoDB

version: '3.8'

services:
  bot-factory:
    build: .
    container_name: bot-factory
    restart: unless-stopped
    environment:
      - API_ID=17490746
      - API_HASH=ed923c3d59d699018e79254c6f8b6671
      - BOT_TOKEN=8020231543:AAHFLDS8a77eqGA045YZFV8uQjvr34IvWrM
      - MONGO_DB_URI=mongodb+srv://huSeen96:Huseenslah96@cluster0.ld2v7.mongodb.net/bot_factory?retryWrites=true&w=majority&appName=Cluster0
      - OWNER_ID=985612253
      - CHANNEL=https://t.me/K55DD
      - GROUP=https://t.me/YMMYN
      - PHOTO=https://t.me/MusicxXxYousef/90
      - VIDEO=https://t.me/MusicxXxYousef/91
      - LOGS=xjjfjfhh
    volumes:
      - ./Maked:/app/Maked
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - bot-network

  mongodb:
    image: mongo:6.0
    container_name: bot-factory-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=bot_factory
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - bot-network

volumes:
  mongodb_data:

networks:
  bot-network:
    driver: bridge